theme: jekyll-theme-minimal
title: Networking, a key to success in the movie industry ?
description: Project 3 : Data Story 
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
