theme: jekyll-theme-minimal
title: Networking
description: Project_3
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Case Study
    url: Case_study
  - title: Conclusion
    url: Conclusion
